### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by vykeer** [kgish/assembla-to-jira-migration#34]
Hey guys!

Have you experienced any problems with JIRA_HEADERS_ADMIN ? 

Every time I use it, it returns NOK 401 - unauthorised.. Jira integrated with gmail, email and API key used

**Comment by kgish** [comment]
Sorry, but only basic authentication is supported. This could be done, but would involve extra work by me. Otherwise I welcome anyone else to implement it and create a pull request.

**Comment by bhoslepu** [comment]
I am using authentication method as in code. Till date there was no problem but all of sudden today I am getting same error:

```
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/json/common.rb:156:in `parse': 743: unexpected token at '<html> (JSON::ParserError)
<head>
    <title>Unauthorized (401)</title>
.
.
.
</head>
<body id="jira" class="aui-layout aui-style-default page-type-message"  data-version="1001.0.0-SNAPSHOT" >
    <div class="aui-page-panel"><div class="aui-page-panel-inner">
            <section class="aui-page-panel-content">
                    <header class="aui-page-header"><div class="aui-page-header-inner">
                            <div class="aui-page-header-main">
                                    <h1>Unauthorized (401)</h1>
                                </div><!-- .aui-page-header-main -->
                        </div><!-- .aui-page-header-inner --></header><!-- .aui-page-header -->
                    <div class="aui-message aui-message-warning warning">
                            <p>Encountered a <code>&quot;401 - Unauthorized&quot;</code> error while loading this page.</p>
                            <p><a href="/secure/MyJiraHome.jspa">Go to Jira home</a></p>
                        </div>
                </section><!-- .aui-page-panel-content -->
        </div><!-- .aui-page-panel-inner --></div><!-- .aui-page-panel -->
</body>
</html>
'
        from /usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/json/common.rb:156:in `parse'
        from 11-jira_import_tickets-new.rb:466:in `rescue in create_ticket_jira'
        from 11-jira_import_tickets-new.rb:445:in `create_ticket_jira'
        from 11-jira_import_tickets-new.rb:892:in `block in <main>'
        from 11-jira_import_tickets-new.rb:880:in `each'
        from 11-jira_import_tickets-new.rb:880:in `each_with_index'
        from 11-jira_import_tickets-new.rb:880:in `<main>'

```

By adding sleep of 1 sec before each API is working fine but adding much much wait time.
I have to import ~17000 tickets, ~800000 comments, ~15000 attachments.  

Using AWS instance (16GB, 4CPU) for doing migration activities, so far assembla export was super fast but hurdled while importing on JIRA Cloud. Before it was a local VM during testing phase.

Does high configuration of machine causing problem? **Is any solution?**

**Comment by kgish** [comment]
I am sorry, but based on the information you have provided it is impossible for me to discover the cause of the problem. I have no experience using an AWS instance for this, why not stay with the VM when it was working fine?

**Comment by QlikChristinaJenks** [comment]
@vykeer This might have been fixed by https://github.com/kgish/assembla-to-jira-migration/issues/37 so give it a shot again?

We're also on AWS. At least in our case, problem was literally sending an incorrect auth header due to how Base64.encode64 works.
